### ISSUE TITLE
Deleting a source file during `sync-glob --watch` generates `ERROR Path must be a string.` on Windows 10

### ISSUE THREAD

**Issue by KeithGillette** [AndyOGo/node-sync-glob#40]
When running:

`sync-glob --watch 'source/*' destination`

Deleting `source/delete.me` generates the following error:

`ERROR Path must be a string. Received [ 'source\\delete.me', 'destination\\delete.me' ]`

With:
- sync-glob 1.3.6
- 3.10.10
- Node 6.9.5
- Windows_NT 10.0.14393

**Comment by AndyOGo** [comment]
@KeithGillette 
Thanks for your detailed bug report.

Interestingly I had the exact same bug on OSX - but fixed it there.

I am happy to create a additional test case, but I don't have a box with windows 10...

**Comment by AndyOGo** [comment]
@KeithGillette 
I just found, unfortunately I just have automated test for my API, but still not for the CLI wrapper.
It was a oneliner. I quickly tested it my CLI on OSX and just released a patch `1.3.7`.

Hope everythings for you know 😉
