### ISSUE TITLE
allow not return output

### ISSUE THREAD

**Issue by nathanredblur** [AndyOGo/node-sync-glob#51]
Will be nice to have a `-silent` mode to not return output. This to prevent long logs in jenkins on do my deploys.

**Comment by AndyOGo** [comment]
@nathanredblur 
Meanwhile you can redirect `/dev/null`

**Comment by AndyOGo** [comment]
@nathanredblur 
Thanks for your suggestion., I just release `1.4.0` with a `--silent` or `-s` option
